FROM apache/airflow:2.8.4-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-17-jre-headless \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

USER airflow

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt \
    && pip install --no-cache-dir apache-airflow-providers-apache-spark==4.8.0

COPY --chown=airflow:root src/ /app/src/
COPY --chown=airflow:root config/ /app/config/
COPY --chown=airflow:root dags/ /opt/airflow/dags/

ENV PYTHONPATH=/app/src
ENV SPARK_MASTER=local[*]
